language: java
jdk:
  - oraclejdk8
env:
  - DEPLOY_USERNAME=travis DEPLOY_PASSWORD=secret
services:
  - cassandra
before_install:
  - gradle -v
  - wget http://services.gradle.org/distributions/gradle-2.2-bin.zip
  - unzip gradle-2.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.2
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - wget http://ftp.ps.pl/pub/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -xzf zookeeper-3.4.6.tar.gz
  - cd zookeeper-3.4.6
  - bin/zkServer.sh start conf/zoo_sample.cfg
after_failure:
  - gradle printTestErrors