language: java
sudo: reguired
jdk:
  - oraclejdk8
env:
  - DEPLOY_USERNAME=travis DEPLOY_PASSWORD=secret
services:
  - cassandra
before_install:
  - wget http://ftp.ps.pl/pub/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -xzf zookeeper-3.4.6.tar.gz
  - cd zookeeper-3.4.6
  - bin/zkServer.sh start conf/zoo_sample.cfg
  - cd ..
after_failure:
  - gradle printTestErrors
